config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  get 'mail/new'

  resources :states

  get "missions/inbox", to: "missions#show"
  post "missions/inbox", to: "missions#capture"
  post "missions/:id", to: "missions#capture"
  resources :missions

  resources :resources

  get "clams/:id/snippet", to: "clams#show_snippet"
  resources :clams

  post "users/authorize_application", to: "users#authorize_application"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               passwords: 'users/passwords',
               sessions: 'users/sessions',
               unlocks: 'users/unlocks',
               invitations: 'users/invitations'
             }
  devise_scope :user do
    get "users/edit/profile" => "users/registrations#edit_profile"
    get "users/edit/applications" => "users/registrations#edit_applications"
  end
  get "users/:id" , to: "users#show"

  get "calendars/import"
  post "calendars/import"
  post "calendars/create_caldav"
  resources :calendars
  resources :recurrences

  get "gate/index"
  get "gate/login"
  get "gate/logout"
  post "gate/login"

  match "events/create_recurrence", :via => :post
  post "events/new"
  get "events/list"

  get "events/input_master_pass", to: "events#input_master_pass"
  post "events/set_token", to: "events#set_token"

  resources :events

  get "inbox/missions"
  get "inbox/recurrences"

  post "recurrences/add_events"
  post "events/ajax_create_event_from_old_event"

end

app/models/recurrence.rb
class Recurrence < ActiveRecord::Base
  has_many :events

  def to_recurrence
    return {
      id: id,
      name: name,
      description: description,
      events: self.events.size
    }
  end

  def self.inbox
    return Recurrence.find_by(name: "inbox")
  end
end

app/controllers/recurrences_controller.rb
class RecurrencesController < ApplicationController
  before_action :set_recurrence, only: [:show, :edit, :update, :destroy]

  # GET /recurrences
  # GET /recurrences.json
  def index
    @recurrences = Recurrence.all

    respond_to do |format|
      format.html
      format.json {render json: Recurrence.all.map(&:to_recurrence)}
    end
  end

  # GET /recurrences/1
  # GET /recurrences/1.json
  def show
  end

  # GET /recurrences/new
  def new
    @recurrence = Recurrence.new
  end

  # GET /recurrences/1/edit
  def edit
  end

  # POST /recurrences
  # POST /recurrences.json
  def create
    @recurrence = Recurrence.new(recurrence_params)

    respond_to do |format|
      if @recurrence.save
        format.html { redirect_to @recurrence, notice: 'Recurrence was successfully created.' }
        format.json { render :show, status: :created, location: @recurrence }
      else
        format.html { render :new }
        format.json { render json: @recurrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recurrences/1
  # PATCH/PUT /recurrences/1.json
  def update
    respond_to do |format|
      if @recurrence.update(recurrence_params)
        format.html { redirect_to @recurrence, notice: 'Recurrence was successfully updated.' }
        format.json { render :show, status: :ok, location: @recurrence }
      else
        format.html { render :edit }
        format.json { render json: @recurrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recurrences/1
  # DELETE /recurrences/1.json
  def destroy
    @recurrence.destroy
    respond_to do |format|
      format.html { redirect_to recurrences_url, notice: 'Recurrence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_last
  recurrence = Recurrence.last
  {recurrence_name: recurrence.name}.to_json
end

  def add_events
    events_id = params[:events_id]== "nil" ? nil : params[:events_id] unless params[:events_id].nil?
    recurrence_id = params[:recurrence_id]== "nil" ? nil : params[:recurrence_id] unless params[:recurrence_id].nil?

    recurrence = Recurrence.find_by(id: recurrence_id)

    events_id.each do |event_id|
      recurrence.events << Event.find_by(id: event_id)
    end

    respond_to do |format|
      format.html {
        flash[:success] = 'Event was successfully add.'
        redirect_to recurrence
      }
      format.json { render json: recurrence }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurrence
      @recurrence = Recurrence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurrence_params
      params.require(:recurrence).permit(:name, :description)
    end
end

app/helpers/recurrences_helper.rb
module RecurrencesHelper
end

app/views/recurrences/_form.html.erb
<%= form_for(@recurrence) do |f| %>
  <% if @recurrence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recurrence.errors.count, "error") %> prohibited this recurrence from being saved:</h2>

      <ul>
      <% @recurrence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recurrences/edit.html.erb
<h1>Editing recurrence</h1>

<%= render 'form' %>

<%= link_to 'Show', @recurrence %> |
<%= link_to 'Back', recurrences_path %>

app/views/recurrences/index.html.erb
<h1>Listing recurrences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recurrences.each do |recurrence| %>
      <tr>
        <td><%= recurrence.name %></td>
        <td><%= recurrence.description %></td>
        <td><%= link_to 'Show', recurrence %></td>
        <td><%= link_to 'Edit', edit_recurrence_path(recurrence) %></td>
        <td><%= link_to 'Destroy', recurrence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recurrence', new_recurrence_path %>

app/views/recurrences/new.html.erb
<h1>New recurrence</h1>

<%= render 'form' %>

<%= link_to 'Back', recurrences_path %>

app/views/recurrences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recurrence.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recurrence.description %>
</p>

<%= link_to 'Edit', edit_recurrence_path(@recurrence) %> |
<%= link_to 'Back', recurrences_path %>