config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  get 'mail/new'

  resources :states

  get "missions/inbox", to: "missions#show"
  post "missions/inbox", to: "missions#capture"
  post "missions/:id", to: "missions#capture"
  resources :missions

  resources :resources

  get "clams/:id/snippet", to: "clams#show_snippet"
  resources :clams

  post "users/authorize_application", to: "users#authorize_application"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               passwords: 'users/passwords',
               sessions: 'users/sessions',
               unlocks: 'users/unlocks',
               invitations: 'users/invitations'
             }
  devise_scope :user do
    get "users/edit/profile" => "users/registrations#edit_profile"
    get "users/edit/applications" => "users/registrations#edit_applications"
  end
  get "users/:id" , to: "users#show"

  get "calendars/import"
  post "calendars/import"
  post "calendars/create_caldav"
  resources :calendars
  resources :recurrences

  get "gate/index"
  get "gate/login"
  get "gate/logout"
  post "gate/login"

  match "events/create_recurrence", :via => :post
  post "events/new"
  get "events/list"

  get "events/input_master_pass", to: "events#input_master_pass"
  post "events/set_token", to: "events#set_token"

  resources :events

  get "inbox/missions"
  get "inbox/recurrences"

  post "recurrences/add_events"
  post "events/ajax_create_event_from_old_event"

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_area :source %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :clam_id %><br>
    <%= f.text_field :clam_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Type</th>
      <th>Clam</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.source %></td>
        <td><%= resource.type %></td>
        <td><%= resource.clam %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @resource.source %>
</p>

<p>
  <strong>Type:</strong>
  <%= @resource.type %>
</p>

<p>
  <strong>Clam:</strong>
  <%= @resource.clam %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>