config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  get 'mail/new'

  resources :states

  get "missions/inbox", to: "missions#show"
  post "missions/inbox", to: "missions#capture"
  post "missions/:id", to: "missions#capture"
  resources :missions

  resources :resources

  get "clams/:id/snippet", to: "clams#show_snippet"
  resources :clams

  post "users/authorize_application", to: "users#authorize_application"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               passwords: 'users/passwords',
               sessions: 'users/sessions',
               unlocks: 'users/unlocks',
               invitations: 'users/invitations'
             }
  devise_scope :user do
    get "users/edit/profile" => "users/registrations#edit_profile"
    get "users/edit/applications" => "users/registrations#edit_applications"
  end
  get "users/:id" , to: "users#show"

  get "calendars/import"
  post "calendars/import"
  post "calendars/create_caldav"
  resources :calendars
  resources :recurrences

  get "gate/index"
  get "gate/login"
  get "gate/logout"
  post "gate/login"

  match "events/create_recurrence", :via => :post
  post "events/new"
  get "events/list"

  get "events/input_master_pass", to: "events#input_master_pass"
  post "events/set_token", to: "events#set_token"

  resources :events

  get "inbox/missions"
  get "inbox/recurrences"

  post "recurrences/add_events"
  post "events/ajax_create_event_from_old_event"

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  acts_as_nested_set
  after_save :rebuild_nested_set
  has_many :clams
  belongs_to :state
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy, :capture], if: :is_valid_id?

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
    @missions = Mission.all
    show_clams = Clam.where("mission_id IS ?", nil)
    show_clams = show_clams.search(params[:search]) if params[:search]
    show_clams = show_clams.narrow_by_reuseinfo if params[:narrow]
    @clams = @mission ? @mission.clams : show_clams.order("date desc")
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def capture
    Clam.transaction do
      clam = Clam.create!(params[:clam])
      clam.resource = Resource.create!(params[:resource])
      if @mission.present?
        @mission.clam = clam
        @Mission.save!
      end
      render json: clam, include: :resource
    end
    rescue => e
      render json: e.message, status: :unprocessable_entity
  end

  def events
    mission_id = params[:id]
    events = Event.where("mission_id is ?", mission_id)
    respond_to do |format|
      format.json { render json: events }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:name, :description, :deadline, :state_id, :keyword, :parent_id, :lft, :rgt, :depth)
    end

    def is_valid_id?
      params[:id].to_i != 0
    end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_clam_list.html.erb
<%= form_tag '/missions/inbox', :method => 'get', :class => 'search' do %>
  <p class="form-inline" align="right">
    <%= check_box_tag :narrow, true, false, {} %>
    <span class="checkbox-caption">Reused mails only</span>
    <%= text_field_tag :search, nil, class: 'form-control', style: 'width:150px' %>
    <i class="fa fa-search search-icon" onclick="$('.search').submit()"></i>
  </p>
<% end %>
<div class="clams-table">
  <table <%= inbox_classes %>>
    <thead>
      <tr>
        <th date-field="summary" data-sortable="false" class="ct-summary">Summary</th>
        <th date-field="date" data-sortable="true" class="ct-date">Date</th>
      </tr>
    </thead>
    <tbody id="tbody_elements">
      <%= render partial: "clam_table", locals: {clams: clams} %>
    </tbody>
  </table>
  <div id="paginator">
    <%= link_to_next_page clams, 'Next', remote: true, class: 'next-page' %>
  </div>
  <div class="related-clam-field"></div>
</div>

app/views/missions/_clam_table.html.erb
<% if clams.present? %>
  <% clams.each do |clam| %>
    <% if clam.fixed == false %>
      <tr class="draggable-clam fixed"
          data-id="<%= clam.id %>"
          data-summary="<%= clam.summary %>">
    <% else %>
      <tr class="draggable-clam"
          data-id="<%= clam.id %>"
          data-summary="<%= clam.summary %>">
    <% end %>
    <td class="show-clam">
      <% if !clam.fixed %>
        <a href="#" class="fa fa-comment-o suggest-icon"></a>
      <% end %>
      <%= clam.summary %>
    </td>
    <td class="show-clam"><%= process_date(clam.date, clam.date) %></td>
    </tr>
  <% end %>
<% end %>

app/views/missions/_create_event_form.html.erb
<div id="create-event-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New Event</h4>
      </div>
      <div class="modal-body">
        <form id="create-event-form">
          <p><b>summary</b></p>
          <input type="text" id="event-summary" class="form-control" style="width:200px;" />
          <br>
          <p><b>date</b><p>
          <input type="text" id="event-dtstart" class="form-control" style="width:150px; display:inline;" /> 〜 <input type="text" id="event-dtend" class="form-control" style="width:150px; display:inline;" />
          <input type="hidden" id="event-allday" />
          <br><br>
          <p><b>Mail</b></p>
          <p class="mail">&nbsp;&nbsp;</p>
          <p><b>Description</b></p>
          <textarea id="event-description" class="form-control"></textarea>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button type="submit" class="btn btn-primary" id="submit-button">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/missions/_create_mission_form.html.erb
<div id="create-mission-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New Mission</h4>
      </div>
      <div class="modal-body">
        <form id="create-mission-form" class="modal-body">
          <p><b>summary</b></p>
          <input type="text" id="mission-summary" class="form-control">
          <p><b>description</b></p>
          <input type="text" id="mission-description" class="form-control">
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button type="submit" class="btn btn-primary" id="submitRecurrenceButton">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/missions/_form.html.erb
<%= form_for(@mission) do |f| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
      <% @mission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :lft %><br>
    <%= f.number_field :lft %>
  </div>
  <div class="field">
    <%= f.label :rgt %><br>
    <%= f.number_field :rgt %>
  </div>
  <div class="field">
    <%= f.label :depth %><br>
    <%= f.number_field :depth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/missions/_mission_list.html.erb
<div class="missions-table">
  <table
     id="table"
     date-class="table table-hover table-bordered table-condensed"
     data-toggle="table"
     data-height="500">
    <thead>
      <tr>
        <th><i class="fa fa-inbox fa-lg"></i> Missions </th>
      </tr>
    </thead>
    <tbody>
      <tr class="mission">
	<td>&nbsp&nbsp<i class="fa fa-folder-o fa-lg"></i> 研究関連 </td>
      </tr>
      <tr class="mission">
	<td>&nbsp&nbsp<i class="fa fa-folder-o fa-lg"></i> 講義 </td>
      </tr>
      <tr class="mission">
	<td>&nbsp&nbsp<i class="fa fa-folder-o fa-lg"></i> 幹事 </td>
      </tr>
      <tr class="mission">
	<td>&nbsp&nbsp<i class="fa fa-folder-o fa-lg"></i> 研究学会 </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render 'form' %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<h1>Listing missions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>State</th>
      <th>Keyword</th>
      <th>Parent</th>
      <th>Lft</th>
      <th>Rgt</th>
      <th>Depth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.name %></td>
        <td><%= mission.description %></td>
        <td><%= mission.deadline %></td>
        <td><%= mission.state_id %></td>
        <td><%= mission.keyword %></td>
        <td><%= mission.parent_id %></td>
        <td><%= mission.lft %></td>
        <td><%= mission.rgt %></td>
        <td><%= mission.depth %></td>
        <td><%= link_to 'Show', mission %></td>
        <td><%= link_to 'Edit', edit_mission_path(mission) %></td>
        <td><%= link_to 'Destroy', mission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission', new_mission_path %>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render 'form' %>

<%= link_to 'Back', missions_path %>

app/views/missions/show.html.erb
<%= javascript_include_tag("missions") %>
<% if @mission.present? %>
  <%= @mission.name %>
  <%= @mission.description %>
  <%= @mission.deadline %>
  <%= @mission.state.name if @mission.state.present? %>
  <%= @mission.keyword %>
  <%= @mission.parent.name if @mission.parent.present? %>
<% end %>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a aria-controls="missions" data-toggle="tab" href="#missions" role="tab">
      <i class="fa fa-folder-open-o fa-2x missions-icon"></i>
    </a>
  </li>
  <li role="presentation">
    <a aria-controls="mini-calendar" data-toggle="tab" href="#mini-calendar" role="tab">
      <i class="fa fa-calendar fa-2x calendar-icon"></i>
    </a>
  </li>
</ul>
<br>
<div class="tab-content" id="tab-con">
  <div role="tabpanel" class="tab-pane active" id="missions">
    <%= render partial: "mission_list", locals: {missions: @missions} %>
  </div>
  <div role="tabpanel" class="tab-pane" id="mini-calendar">
    <div id="calendar" class="mini-calendar"></div>
  </div>
</div>
<%= render partial: "clam_list", locals: {clams: @clams} %>
<%= render partial: "missions/create_event_form" %>